repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: git://github.com/troian/pre-commit-golang
    sha: HEAD
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
    -   id: go-build
    -   id: go-metalinter
        args:
        - --vendor
        - --cyclo-over=12
