env:
  global:
    - CC_TEST_REPORTER_ID=f297b36c064c8cb11ce97885a19959699190a89e0bfc2e0696aa32305be1ed67
language: go
go:
  - 1.9
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./lint.sh
  - ./test.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash)
