language: go
sudo: false
go:
  - 1.9.x

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./lint.sh
  - ./test.sh
  - ./cover.sh

after_script:
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)
