version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/carterjones/signalr
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: ./lint.sh
      - run: ./test.sh
      - run: ./cover.sh
