version: 2
jobs:
  build:
    docker:
      - image: carterjones/infra-builder:latest
    working_directory: /go/src/github.com/carterjones/signalr
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: ./lint.sh
      - run: ./test.sh
      - run: ./cover.sh
